append basic DNS configuration in bootstrap if missing (#32914)
This is critical to make Puppet bootstrap properly. If the domain
search is not setup correctly, Puppet will not find the `puppet`
domain and will fail to bootstrap itself.

This step should be done by the system installer, but it's possible it
failed at its job, either because it's buggy, incomplete, or that it
has a different set of assumptions than we do.

By appending the `domain` line, we make sure `puppet` will resolve to
`puppet.torproject.org` which should bootstrap Puppet. We also add a
dummy nameserver there (Google, for a lack of a better, well-known,
and public alternative) just in case `resolv.conf` really *is* badly
configured.

That configuration should be overriden by Puppet on the first run,
when the local resolver is installed.

diff --git a/installer/puppet-bootstrap-client b/installer/puppet-bootstrap-client
--- a/installer/puppet-bootstrap-client
+++ b/installer/puppet-bootstrap-client
@@ -5,6 +5,22 @@ set -u
 
 domain=torproject.org
 
+# give our installer a chance at failing a proper setup
+#
+# XXX: should we just check if "host puppet" resolves instead of taking this guess?
+if ! grep "^domain $domain\$" /etc/resolv.conf ; then
+    echo "missing ${domain} from /etc/resolv.conf, appending backup configuration..."
+    cat >> /etc/resolv.conf <<EOF
+
+# fallback configuration added by $0 on $(date +%Y-%m-%d)
+domain $domain
+
+# bootstrap DNS for Puppet with Google, should be replaced by next Puppet run
+nameserver 8.8.8.8
+
+EOF
+fi
+
 # sanity check
 if ! [ "$(hostname).${domain}" = "$(hostname -f)" ]; then
     echo "Error: hostname '$(hostname -f)' doesn't match expected domain '$(hostname).$domain'"
